/**
 * Tool call display component - Claude Code style.
 * Supports text truncation with Ctrl+O toggle.
 */
import React from 'react';
import { Text, Box } from 'ink';
import { Spinner } from './Spinner.js';
import { MarkdownText } from './MarkdownText.js';
import { TruncatedText } from './TruncatedText.js';

/** Maximum lines to show before truncation */
const MAX_LINES_TRUNCATED = 3;

interface ToolCallDisplayProps {
  toolName: string;
  args?: Record<string, unknown>;
  status?: 'executing' | 'completed' | 'error' | 'needs_confirmation';
  result?: unknown;
  duration?: number;
  compact?: boolean;
  /** Expanded view mode (kept for API compatibility but no longer used) */
  expanded?: boolean;
  /** Name of the agent that invoked this tool */
  agentName?: string;
  /** Streaming content being generated by sub-agent loops */
  streamingContent?: string;
  /** Whether streaming content was already displayed live */
  wasStreamed?: boolean;
}

// Tools that should be hidden (rendered elsewhere in UI)
export const HIDDEN_TOOLS = new Set(['TodoWrite', 'todo_write']);

// Tools with special rendering (not standard tool call format)
const SPECIAL_RENDER_TOOLS = new Set(['think', 'dispatch_agent']);

// User-friendly display names with gerund (ongoing) and past tense (completed)
const TOOL_DISPLAY_NAMES: Record<string, { gerund: string; past: string }> = {
  think: { gerund: 'Thinking', past: 'Thought' },
  AskUserQuestion: { gerund: 'Asking user', past: 'Asked user' },
  ask_user: { gerund: 'Asking user', past: 'Asked user' },
  dispatch_agent: { gerund: 'Dispatching agent', past: 'Dispatched agent' },
  generate_image: { gerund: 'Generating image', past: 'Generated image' },
  generate_video: { gerund: 'Generating video', past: 'Generated video' },
  edit_image: { gerund: 'Editing image', past: 'Edited image' },
  wait_for_job: { gerund: 'Waiting for job', past: 'Job completed' },
  read_file: { gerund: 'Reading file', past: 'Read file' },
  generate_content: { gerund: 'Generating content', past: 'Generated content' },
  list_project_files: { gerund: 'Listing project files', past: 'Listed project files' },
};

// Tools whose results should be truncated to a few lines
const TRUNCATE_RESULT_TOOLS = new Set(['read_file']);

/** Truncate text to N lines and add "..." if truncated */
function truncateToLines(text: string, maxLines: number): { text: string; truncated: boolean } {
  const lines = text.split('\n');
  if (lines.length <= maxLines) {
    return { text, truncated: false };
  }
  return { text: lines.slice(0, maxLines).join('\n') + '\n...', truncated: true };
}

function getDisplayName(toolName: string, isExecuting: boolean): string {
  const names = TOOL_DISPLAY_NAMES[toolName];
  if (!names) {
    // Generate default gerund/past for unknown tools
    return isExecuting ? `Running ${toolName}` : `Ran ${toolName}`;
  }
  return isExecuting ? names.gerund : names.past;
}

// Format duration in human-readable form
function formatDuration(ms: number): string {
  if (ms < 1000) return `${String(ms)}ms`;
  if (ms < 60000) return `${(ms / 1000).toFixed(1)}s`;
  return `${String(Math.floor(ms / 60000))}m ${String(Math.floor((ms % 60000) / 1000))}s`;
}

/** Maximum characters for string arguments before truncation */
const MAX_ARG_LENGTH = 80;

/** Arguments that contain long content and should be truncated */
const CONTENT_ARGS = new Set(['content', 'data', 'text', 'body', 'message']);

// Truncate a string with ellipsis
function truncateString(str: string, maxLength: number): string {
  if (str.length <= maxLength) return str;
  return str.slice(0, maxLength) + '...';
}

// Format tool call in Claude Code style: toolName(arg1="val", arg2=...)
function formatToolCall(name: string, args?: Record<string, unknown>): string {
  if (!args || Object.keys(args).length === 0) {
    return `${name}()`;
  }

  const parts: string[] = [];
  for (const [key, value] of Object.entries(args)) {
    if (typeof value === 'string') {
      // Truncate content-type arguments more aggressively
      const maxLen = CONTENT_ARGS.has(key) ? MAX_ARG_LENGTH : MAX_ARG_LENGTH * 2;
      const displayValue = truncateString(value.replace(/\n/g, '\\n'), maxLen);
      parts.push(`${key}="${displayValue}"`);
    } else if (typeof value === 'number' || typeof value === 'boolean') {
      parts.push(`${key}=${String(value)}`);
    } else if (Array.isArray(value)) {
      const jsonStr = JSON.stringify(value);
      parts.push(`${key}=${truncateString(jsonStr, MAX_ARG_LENGTH)}`);
    } else if (value !== null && typeof value === 'object') {
      const jsonStr = JSON.stringify(value);
      parts.push(`${key}=${truncateString(jsonStr, MAX_ARG_LENGTH)}`);
    }
  }

  return `${name}(${parts.join(', ')})`;
}

function getStatusIcon(status: ToolCallDisplayProps['status']): { icon: string; color: string } {
  switch (status) {
    case 'executing':
      return { icon: '◉', color: 'yellow' };
    case 'completed':
      return { icon: '✓', color: 'green' };
    case 'error':
      return { icon: '✗', color: 'red' };
    case 'needs_confirmation':
      return { icon: '?', color: 'cyan' };
    default:
      return { icon: '○', color: 'gray' };
  }
}

// Render think tool specially
function renderThinkTool(
  args: Record<string, unknown> | undefined,
  status: ToolCallDisplayProps['status'],
  duration?: number
): React.ReactNode {
  const thought = args?.['thought'] as string | undefined;
  const isExecuting = status === 'executing';

  return (
    <Box flexDirection="column">
      <Box>
        {isExecuting ? (
          <>
            <Text>💭 </Text>
            <Spinner />
          </>
        ) : (
          <>
            <Text>💭 </Text>
            <Text italic color="white">
              {thought || 'Thinking...'}
            </Text>
          </>
        )}
      </Box>
    </Box>
  );
}

// Render dispatch_agent (planning) tool specially
function renderDispatchAgentTool(
  args: Record<string, unknown> | undefined,
  status: ToolCallDisplayProps['status'],
  result?: unknown,
  expanded?: boolean
): React.ReactNode {
  const task = args?.['task'] as string | undefined;
  const context = args?.['context'] as string | undefined;
  const isExecuting = status === 'executing';

  // Extract plan from result
  const resultObj = result as Record<string, unknown> | undefined;
  const plan = resultObj?.['plan'] as string | undefined;

  return (
    <Box flexDirection="column" borderStyle="round" borderColor="blue" paddingX={1} marginY={1}>
      <Box>
        {isExecuting ? (
          <>
            <Text color="blue">📝 </Text>
            <Spinner color="blue" />
            <Text color="blue"> Planning...</Text>
          </>
        ) : (
          <Text color="blue" bold>
            📝 Plan Complete
          </Text>
        )}
      </Box>
      <Box flexDirection="column" marginLeft={2} marginTop={1}>
        <Box flexDirection="column">
          <Text bold color="yellow">
            Task:{' '}
          </Text>
          <TruncatedText
            text={task || 'No task specified'}
            maxLines={MAX_LINES_TRUNCATED}
            expanded={expanded}
          />
        </Box>
        {context && (
          <Box flexDirection="column" marginTop={1}>
            <Text bold color="yellow">
              Context:{' '}
            </Text>
            <TruncatedText
              text={context}
              maxLines={MAX_LINES_TRUNCATED}
              expanded={expanded}
              dimColor
            />
          </Box>
        )}
        {plan && !isExecuting && (
          <Box flexDirection="column" marginTop={1}>
            <Text bold color="green">
              Plan:
            </Text>
            <Box marginTop={1} marginLeft={1} flexDirection="column">
              {expanded ? (
                <MarkdownText text={plan} />
              ) : (
                <TruncatedText text={plan} maxLines={MAX_LINES_TRUNCATED} expanded={false} />
              )}
            </Box>
          </Box>
        )}
      </Box>
    </Box>
  );
}

// Render read_file tool specially with truncated content
function renderReadFileTool(
  args: Record<string, unknown> | undefined,
  status: ToolCallDisplayProps['status'],
  result?: unknown,
  duration?: number,
  agentName?: string
): React.ReactNode {
  const filePath =
    (args?.['file_path'] as string | undefined) ?? (args?.['path'] as string | undefined);
  const isExecuting = status === 'executing';
  const isError = status === 'error';

  // Extract file content from result
  let fileContent: string | undefined;
  let truncatedContent: string | undefined;
  let wasTruncated = false;

  if (!isExecuting && result) {
    if (typeof result === 'string') {
      fileContent = result;
    } else if (typeof result === 'object') {
      const resultObj = result as Record<string, unknown>;
      if (typeof resultObj['content'] === 'string') {
        fileContent = resultObj['content'];
      } else if (typeof resultObj['error'] === 'string') {
        fileContent = resultObj['error'];
      }
    }

    if (fileContent && !isError) {
      const truncResult = truncateToLines(fileContent, 3);
      truncatedContent = truncResult.text;
      wasTruncated = truncResult.truncated;
    }
  }

  // Get just the filename from the path
  const fileName = filePath ? filePath.split('/').pop() : 'unknown';

  return (
    <Box
      flexDirection="column"
      borderStyle="round"
      borderColor={isError ? 'red' : isExecuting ? 'yellow' : 'green'}
      paddingX={1}
      marginY={1}
    >
      <Box>
        {isExecuting ? (
          <>
            <Text color="yellow">◉ </Text>
            <Spinner />
            <Text> Reading file</Text>
            {agentName && (
              <Text color="cyan" dimColor>
                {' '}
                [{agentName}]
              </Text>
            )}
          </>
        ) : (
          <>
            <Text color={isError ? 'red' : 'green'}>{isError ? '✗' : '✓'} </Text>
            <Text>Read file</Text>
            {agentName && (
              <Text color="cyan" dimColor>
                {' '}
                [{agentName}]
              </Text>
            )}
            {duration !== undefined && <Text dimColor> ({formatDuration(duration)})</Text>}
          </>
        )}
      </Box>
      <Box marginLeft={2}>
        <Text dimColor>read_file(path="{fileName}")</Text>
      </Box>
      {isError && fileContent && (
        <Box marginLeft={2} marginTop={1}>
          <Text color="red">{fileContent}</Text>
        </Box>
      )}
      {!isExecuting && !isError && truncatedContent && (
        <Box marginLeft={2} marginTop={1} flexDirection="column">
          <Text dimColor>{truncatedContent}</Text>
          {wasTruncated && (
            <Text color="gray" italic>
              {' '}
              (content truncated)
            </Text>
          )}
        </Box>
      )}
    </Box>
  );
}

export const ToolCallDisplay = React.memo(function ToolCallDisplay({
  toolName,
  args,
  status = 'executing',
  result,
  duration,
  compact = false,
  expanded = false,
  agentName,
  streamingContent,
  wasStreamed = false,
}: ToolCallDisplayProps) {
  // Special rendering for think tool
  if (toolName === 'think') {
    return renderThinkTool(args, status, duration);
  }

  // Special rendering for dispatch_agent (planning) tool
  if (toolName === 'dispatch_agent') {
    return renderDispatchAgentTool(args, status, result, expanded);
  }

  // Special rendering for read_file tool
  if (toolName === 'read_file') {
    return renderReadFileTool(args, status, result, duration, agentName);
  }

  // Standard tool display
  const isExecuting = status === 'executing';
  const displayName = getDisplayName(toolName, isExecuting);
  const statusIcon = getStatusIcon(status);
  const toolCallStr = formatToolCall(toolName, args);

  // For completed tools, extract content from result if available (used by Task tools)
  // This allows streaming content to show during execution, and result.content after completion
  // Skip if wasStreamed is true - content was already displayed live during streaming
  const resultContent = React.useMemo(() => {
    if (isExecuting || streamingContent || wasStreamed) return undefined;
    if (result && typeof result === 'object') {
      const resultObj = result as Record<string, unknown>;
      const content = resultObj['content'];
      if (typeof content === 'string' && content.length > 0) {
        return content;
      }
    }
    return undefined;
  }, [isExecuting, streamingContent, wasStreamed, result]);

  if (compact) {
    return (
      <Box
        flexDirection="column"
        borderStyle="round"
        borderColor={statusIcon.color}
        paddingX={1}
        marginY={1}
      >
        <Box>
          {isExecuting ? (
            <>
              <Text color="yellow">◉ </Text>
              <Spinner />
              <Text> {displayName}</Text>
              {agentName && (
                <Text color="cyan" dimColor>
                  {' '}
                  [{agentName}]
                </Text>
              )}
            </>
          ) : (
            <>
              <Text color={statusIcon.color}>{statusIcon.icon} </Text>
              <Text>{displayName}</Text>
              {agentName && (
                <Text color="cyan" dimColor>
                  {' '}
                  [{agentName}]
                </Text>
              )}
              {duration !== undefined && <Text dimColor> ({formatDuration(duration)})</Text>}
            </>
          )}
        </Box>
        <Box marginLeft={2}>
          <Text dimColor wrap="wrap">{toolCallStr}</Text>
        </Box>
        {status === 'error' && result !== undefined && (
          <Box marginLeft={2}>
            <Text color="red" wrap="wrap">
              Error: {typeof result === 'object' ? JSON.stringify(result) : String(result)}
            </Text>
          </Box>
        )}
        {streamingContent && (
          <Box marginLeft={2} marginTop={1} flexDirection="column">
            <MarkdownText text={streamingContent} />
          </Box>
        )}
        {resultContent && (
          <Box marginLeft={2} marginTop={1} flexDirection="column">
            <MarkdownText text={resultContent} />
          </Box>
        )}
      </Box>
    );
  }

  // Full (non-compact) display
  return (
    <Box
      flexDirection="column"
      borderStyle="round"
      borderColor={statusIcon.color}
      paddingX={1}
      marginY={1}
    >
      <Box>
        {isExecuting ? (
          <>
            <Text color="yellow">◉ </Text>
            <Spinner />
            <Text bold> {displayName}</Text>
            {agentName && (
              <Text color="cyan" dimColor>
                {' '}
                [{agentName}]
              </Text>
            )}
          </>
        ) : (
          <>
            <Text color={statusIcon.color}>{statusIcon.icon} </Text>
            <Text bold>{displayName}</Text>
            {agentName && (
              <Text color="cyan" dimColor>
                {' '}
                [{agentName}]
              </Text>
            )}
            {duration !== undefined && <Text dimColor> ({formatDuration(duration)})</Text>}
          </>
        )}
      </Box>

      <Box marginLeft={2}>
        <Text dimColor>{toolCallStr}</Text>
      </Box>

      {status === 'error' && result !== undefined && (
        <Box marginLeft={2}>
          <Text color="red">
            Error: {typeof result === 'object' ? JSON.stringify(result) : String(result)}
          </Text>
        </Box>
      )}

      {streamingContent && (
        <Box marginLeft={2} marginTop={1} flexDirection="column">
          <MarkdownText text={streamingContent} />
        </Box>
      )}
      {resultContent && (
        <Box marginLeft={2} marginTop={1} flexDirection="column">
          <MarkdownText text={resultContent} />
        </Box>
      )}
    </Box>
  );
});
